# Disable the "core" varnish plugins
disablePlugins:
  - lando-varnish

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/varnish": /home/runner/work/varnish/varnish

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
