name: lando-varnish-custom
services:
  custom:
    type: varnish:6.0
    backends:
      - appserver
    ssl: true
    overrides:
      environment:
        MEGAMAN: X
    config:
      vcl: config/custom.vcl
  customport:
    type: varnish:6
    backends:
      - backend2
    backend_port: 8000
    ssl: true
  appserver:
    type: nginx
  backend2:
    type: python
    port: 8000
    command: python /app/python.py
  curly:
    api: 4
    image: curlimages/curl
    command: sleep infinity

tooling:
  curl:
    service: curly

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/varnish": ./../../
  "@lando/python": ./../../node_modules/@lando/python
  "@lando/nginx": ./../../node_modules/@lando/nginx
