name: lando-varnish
services:
  custom:
    type: varnish:4
    backends:
      - appserver
    ssl: true
    overrides:
      environment:
        MEGAMAN: X
    config:
      vcl: config/custom.vcl
  customport:
    type: varnish:6
    backend: backend2
    backend_port: 8000
    ssl: true
  appserver:
    type: nginx
  backend2:
    type: python
    port: 8000
    command: python /app/python.py
  curl:
    api: 4
    image: curlimages/curl:8.10.1
    command: sleep infinity

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/varnish": ../..
  "@lando/nginx": ../../node_modules/@lando/nginx
  "@lando/python": ../../node_modules/@lando/python
